version: '2'

services:
  db:
    networks:
      - default
    build:
      context: ./dockerfiles
      dockerfile: postgres_server
    container_name: db
    ports:
      - "5432:5432"
    image: almer8/postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: ./dockerfiles
      dockerfile: java_app
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    image: almer8/noteskeeper
  pga:
    container_name: pga
    build:
      context: ./dockerfiles
      dockerfile: postgres_pga
    networks:
      - default
    depends_on:
      - db
    ports:
      - "5333:80"
    image: almer8/pgadmin
  frontend:
    container_name: frontend
    networks:
      - default
    depends_on:
      - app
    ports:
      - "3000:3000"
    image: almer8/noteskeeper-frontend

volumes:
  postgres-data: {}
networks:
  default:
    driver: bridge
